highlighter: rouge
permalink: none
kramdown:
  input: GFM
  hard_wrap: false
repository: sb2nov/sb2nov.github.io
plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-seo-tag
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: /blog/:year/:month/:day/:title/
google_analytics: 'UA-40495390-2'
title: Sourabh
description: Sourabh's portfolio and writings on machine learning, data science and distributed systems.
url: https://sourabhbajaj.com
author: Sourabh Bajaj
twitter:
  username: sb2nov
logo: images/contents/NN.png
social:
  name: Sourabh
  links:
    - https://twitter.com/sb2nov
    - https://www.linkedin.com/in/sbajaj9
    - https://github.com/sb2nov
    - https://speakerdeck.com/sb2nov/
